# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Guide-iOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Guide-iOS
  pod 'SwiftyBeaver', '~> 1.5'
  pod 'Alamofire', '~> 4.6'
  pod 'ObjectMapper', '~> 2.2'
  
  target 'Guide-iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Guide-iOSUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
